### ISSUE TITLE
add Progress bar to mondrian

### ISSUE THREAD

**Issue by luzpaz** [outilslibresalternatifs/scribus-scripts#10]
It takes about 55 sec for the mondrian script to complete. 
Would it be possible to add a progress bar message or indicator like this script has:
http://wiki.scribus.net/canvas/Scrambling_Text#replacetext_v3.py
Or just look at [line 38](http://pastebin.com/Cc4QWDeC)

Edit: adding [link](https://www.dropbox.com/s/t6u0ansvxgwvjz3/mondrian.mov?dl=0) to clip loading the script:

**Comment by sarahgarcin** [comment]
Ok, i'll fix that. Thanks for the example.

**Comment by luzpaz** [comment]
Error: 

> Traceback (most recent call last):
>  File "<string>", line 8, in <module>
>  File "/Volumes/Macintosh HD/Users/sphenoid/Applications/Scribus.app/Contents/share/scribus/scripts/mondrian.py", line 81, in <module>
>    main_wrapper(sys.argv)
>  File "/Volumes/Macintosh HD/Users/sphenoid/Applications/Scribus.app/Contents/share/scribus/scripts/mondrian.py", line 73, in main_wrapper
>    main(argv)
>  File "/Volumes/Macintosh HD/Users/sphenoid/Applications/Scribus.app/Contents/share/scribus/scripts/mondrian.py", line 51, in main
>     scribus.progressSet(i*2)
> ValueError: Tried to set progress > maximum progress

OSX 10.10.4 running 1.5.1 r20315 Qt5.5

**Comment by luzpaz** [comment]
ping @sarahgarcin
