### ISSUE TITLE
imagegrid localization

### ISSUE THREAD

**Issue by luzpaz** [outilslibresalternatifs/scribus-scripts#8]
Variables translated to english
docWidthStr1 = 'Paper Width'
docWidthStr2 = 'Enter the width of your document (in mm)'
docHeightStr1 = 'Document Height'
docHeightStr2 = 'Please enter the height of your document (in mm)'
numColStr1 = 'Number of columns'
numColStr2 = 'How many columns? '
numLinStr1 = 'Number of Lines'
numLinStr2 = 'How many lines?'
gapStr1 = 'Margin Width'
gapStr2 = 'What is the margin width (in mm)?'

**Comment by luzpaz** [comment]
CC @sarahgarcin

**Comment by luzpaz** [comment]
We can use [transifex](https://www.transifex.com/projects/p/scribus/)?

**Comment by sarahgarcin** [comment]
Yes great idea! thanks

**Comment by sarahgarcin** [comment]
Transifex is not a free service...

**Comment by sarahgarcin** [comment]
Can't find a solution for localization, so I translate every strings in english.
